# cluster specific values
cluster:
  name: my-nice-cluster

# specify cloud credential secret name, do not need to be provided if using custom driver
cloudCredentialSecretName: "cattle-global-data:cc-b6hkn"

# specify cloud provider, options are amazonec2, digitalocean, azure, vsphere or custom
cloudprovider: "harvester"

kubernetesVersion: "v1.24.4+rke2r1"

# enable monitoring
monitoring:
  enabled: true
  # specify which version to install, can be semver range. If version is empty or is semver range, it will pick up the latest version.
  # version: ""
  # specify cutsom values set
  # values:
  #   foo: bar
  #
rke:
  localClusterAuthEndpoint:
    enabled: false

networkSeparation:
  enabled: false

nodepools:
- etcd: true
  controlplane: true
  worker: true

  # specify node labels
  labels: {}

  # specify node taints
  taints: {}

  # specify nodepool size
  quantity: 3

  name: harvester-nodepool-1
  diskSize: 40
  diskBus: virtio
  cpuCount: 4
  memorySize: 8
  networkName: default/lab
  imageName: default/image-6jv96
  vmNamespace: default
  sshUser: ubuntu
